# Generated by Django 4.0.3 on 2022-04-05 08:01

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_contact_email_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2022, 4, 5, 8, 0, 48, 951404, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='filelink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
