# Generated by Django 4.0.3 on 2022-04-05 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_contact_createtime_contact_filelink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='createtime',
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
