# Generated by Django 4.0.3 on 2022-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0006_remove_contact_filelink_contact_fileupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
