# Generated by Django 4.0.3 on 2022-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0008_contact_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
