# Generated by Django 4.0.3 on 2022-04-09 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0009_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='moderatorreply',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
