# Generated by Django 4.0.3 on 2022-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0010_contact_moderatorreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='moderatorreply',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
