# Generated by Django 4.0.3 on 2022-04-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0011_alter_contact_moderatorreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='moderatorreply',
            new_name='manager_reply',
        ),
    ]
