# Generated by Django 4.0.3 on 2022-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0012_rename_moderatorreply_contact_manager_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fileupload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
